### ISSUE TITLE
Interface JSON - Elastic Search

### ISSUE THREAD

**Issue by ThiagoTrabach** [labFGV/DOliberto#7]
- [ ] criar ambiente ES #6 (v0.1) 

- [ ] ler JSON pra base (v0.1) 

- [ ] profit??

**Comment by odanoburu** [comment]
see above: não vai ser mais TOML

---

pq TOML? https://npf.io/2014/08/intro-to-toml/
repo: https://github.com/toml-lang/toml

dummy DO:

```toml
[2017-08-17]
autor="léo"
    [2017-08-17.sme.1]
    autoridade = "fulana de tal"
    valor = 10
    texto = """lorem ipsum 10 reais assinado: fulana de tal"""
```

**Comment by odanoburu** [comment]
dummy DO:

```toml
[2017-08-17]
autor="léo"
    [2017-08-17.sme.1]
    autoridade = "fulana de tal"
    valor = 10
    texto = """lorem ipsum 10 reais assinado: fulana de tal"""
```
